### ISSUE TITLE
Unable to run Contentful Compose migrations scripts

### ISSUE THREAD

**Issue by thomas-ej-mcdonald** [contentful/contentful-cli#1050]
## Expected Behavior

Using the experimental version of the CLI for migrations should allow me to use the `relationshipType` validation on a field to work with Compose.

Followed steps on [this page](https://www.contentful.com/developers/docs/compose/cli-tools/)

## Actual Behavior

Error in regards to `relationshipType` validation.

```
Error: A field can't have "relationshipType" as a validation.
Error: A field can't have "relationshipType" as a validation.

Publish Content Type page
🚨  Migration unsuccessful
🚨  Error: Validation Errors
┌──────────────────────────────────────────────────────────────────────────────┐
│ Error: Validation Errors                                                     │
│     at run                                                                   │
│ (/usr/local/lib/node_modules/contentful-cli/node_modules/contentful-migrati… │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)      │
```

## Possible Solution

Someone I know has the CLI working when the `contentful-migration` dependency of the CLI is set to `4.2.0-experimental.4`.

After installing the `contentful-cli@experimental` package locally and looking at the `package-lock.json`, the `contentful-migration` dependency is set to `"contentful-migration": "^4.2.0-experimental.1"`. However, the actual version being installed when installing the CLI locally and globally is `4.2.3`. This makes sense to me since the version set will allow for newer minor and patch versions to be installed. The experimental patch version would probably need to be fixed in order to consistently get it.

## Steps to Reproduce

1. Have tried with Node versions 12 and 14.
2. `npm cache clean --force`
3. `npm install -g contentful-cli@experimental`
4. `npm list -ag | grep contentful` -> shows `contentful-migration@4.2.3` as the CLI dependency
4. `contentful space migration --space-id <space-id> --environment-id <env> --management-token <mgmt-token> --header "x-contentful-enable-alpha-feature: assembly-types" <migration-script-file.js>` using an example like this one [here](https://www.contentful.com/developers/docs/compose/cli-tools/#add-a-new-page-type-to-compose)
5. Error above is shown

## Context

I am trying to run migration scripts that work with Contentful Compose via the CLI. Specifically, I am creating a new page type and am updating the `page` content type to link to the my new page type. Looks essentially the same as example [here](https://www.contentful.com/developers/docs/compose/cli-tools/#add-a-new-page-type-to-compose).

I am completely unable to run my migration scripts that work with Compose which is blocking us.

Observations and things I've tried:
* Cleared npm cache
* Different Node/NPM versions (node 14 and 12)
* Manual global install of experimental contentful-migration package before global install of contentful-cli@experimental
* Local installation
* Installing contentful-cli using the `--save-exact` npm install flag and the `--strict-peer-deps` flags

## Environment

-   **Language Version**: `v14.17.0`
-   **Package Manager Version**: `7.17.0`
-   **Browser Version**: n/a
-   **Operating System**: `Darwin US3CREM00F9JG5J 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64`
-   **Package Version**: `contentful-cli@1.6.3-experimental.1`

Same error occurring with a `node:12.22.1-buster-slim` Docker container running `npm install -g contentful-cli@experimental`

**Comment by marcolink** [comment]
Hi @thomas-ej-mcdonald,

we created a new version where `contentful-migration@4.2.0-experimental.1` is pinned!

**Comment by thomas-ej-mcdonald** [comment]
Thanks! Was able to reinstall and run migrations!

**Comment by marcolink** [comment]
@thomas-ej-mcdonald great to hear - have a nice weekend!

**Comment by thomas-ej-mcdonald** [comment]
@marcolink you as well!

**Comment by vleung-into** [comment]
Hello

Thanks for posting the update, unfortunately it doesn't appear to work for me. I've tried re-installing the package but encounter the same error message as before. Any advice?

Environment
Language Version: v14.15.5
Package Manager Version: 6.14.11
Operating System: Windows 10 Pro - 10.0.19041 Build 19041

Package Version: contentful-cli@1.6.3-experimental.2

**Comment by thomas-ej-mcdonald** [comment]
@vleung-into, out of curiosity, do mind running `npm list -ag | grep contentful`. I want to see what the version for `contentful-migration` is that your CLI is using

**Comment by vleung-into** [comment]
@thomas-ej-mcdonald I'm using powershell, this is the output from select-string "contentful-migration" 

| +-- contentful-migration@4.2.0-experimental.1

**Comment by vleung-into** [comment]
Here's a snippet of the script:

```
const page = migration.editContentType("page");
    page
        .editField("content")
        .validations([
            { linkContentType: ["customPageTemplate"], },
            { relationshipType: ["Composition"], },
        ])
```

Doesn't look out of the ordinary!

**Comment by thomas-ej-mcdonald** [comment]
Yeah, that snippet looks good. I'm looking at https://github.com/contentful/contentful-migration/blob/cd0a9bf622889203258f9bd8551e99101c952411/src/lib/migration-parser.ts to see what I can find. I'll probably take a closer look later (@tmcdo1)

**Comment by tmcdo1** [comment]
@vleung-into , how are you running the migrations? Are you using an npm script or are you directly using the CLI?

**Comment by vleung-into** [comment]
@tmcdo1 I'm using the contentful-cli, and example command: 

```
contentful space migration --environment-id 'test-env' .\up-migration\contentful-migration.js
```
