### ISSUE TITLE
Can you create entries with this CLI tool?

### ISSUE THREAD

**Issue by dagumak** [contentful/contentful-cli#108]
I did not see anything related to creating entries in the README. Is this possible? I mainly want this so I can migrate certain content from another system to Contentful.

**Comment by Khaledgarbaya** [comment]
Hey @dagumak,

Currently, this is available using the CLI tool.
for importing content you might wanna check out the `contentful space import` command

**Comment by dagumak** [comment]
> Hey @dagumak,
> 
> Currently, this is available using the CLI tool.
> for importing content you might wanna check out the `contentful space import` command

Thanks, if my images are hosted on S3 and I build the JSON structure for an entry with a reference to the images, then would Contentful automatically download it from s3? Also, if I omit the following in an entry during import, would Contentful automatically populate this?

```
 "publishedCounter": 2,
        "version": 20,
        "publishedBy": {
          "sys": {
            "type": "Link",
            "linkType": "User",
            "id": "1231451fkafak"
          }
```
