### ISSUE TITLE
Logout always prompts for input, even on CI

### ISSUE THREAD

**Issue by NigeAtAnd** [contentful/contentful-cli#1083]
## Expected Behavior

`contentful logout` supports a method of logging out without prompting the user.

## Actual Behavior

`contentful logout` always prompts for input, making it unusable in situations such as CI.

## Possible Solution

It'd be cool if a parameter could be passed to `contentful logout` to suppress the prompt and immediately logout, e.g. `contentful logout --yes` or `contentful logout --no-prompt`.

## Context

Trying to logout on CI to ensure credentials don't remain on the build machine and `contentful login` works next time. I'm aware I can delete `~/.contentfulrc.json`, but that seems a little hacky given everything else is done through contentful-cli.

## Environment

Any.

-   **Language Version**: NodeJS v14.16.0
-   **Package Manager Version**: NPM 6.14.11
-   **Package Version**: 1.6.19

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
