### ISSUE TITLE
contentful space environment list complains about missing accesToken (though management token is provided)

### ISSUE THREAD

**Issue by jmcazaux** [contentful/contentful-cli#110]
`contentful space environment list` still looks for a token although one is provided

## Expected Behavior

`contentful space environment list --management-Token my-secret-token --space-id my-space-id` should list all environments in space with ID my-space-id. 

## Actual Behavior

Here is the error that I am getting:

> 🚨  Error: Expected parameter accessToken
> TypeError: Expected parameter accessToken                                                                                                                    
> 
>      at createClient (/usr/local/lib/node_modules/contentful-cli/node_modules/contentful-management/dist/contentful-management.node.js:6964:11)
>      at createManagementClient (/usr/local/lib/node_modules/contentful-cli/dist/utils/contentful-clients.js:33:49)
>      at <anonymous>

**Comment by jmcazaux** [comment]
Exact same issue when trying to use `contentful space environment create`.

**Comment by jroehl** [comment]
Fixed by #150
