### ISSUE TITLE
Import stalls at Importing Assets step

### ISSUE THREAD

**Issue by dmbdesignpdx** [contentful/contentful-cli#1136]
## Expected Behavior

Running `contentful space import --environment-id [env] --content-file [file]` should either succeed in importing or fail and give an error.

## Actual Behavior

Running the aforementioned command results in the command stalling out at the _Importing Assets_ step and never exists.

![Screen Shot 2021-09-14 at 5 27 32 PM](https://user-images.githubusercontent.com/5041305/133352670-19b6eda2-3368-436e-a48e-c056f737805d.png)

It's not the asset "scribie-logo"; I've removed it, created a new export file, then imported again and it still gets stuck at the same step processing a different asset.

## Steps to Reproduce

1. `contentful space export --environment-id [env-one] --content-only`
2. `contentful space migration -e [env-two] [file].js`
3. `contentful space import --environment-id [env-two] --content-file [file]`

## Context

I'm using "env-two" as test environment for making sure migration scripts and export/imports work without failing, before migrating content and assets to the main environment.

## Environment

-   **Contentful CLI Version**: 1.9.15
-   **Homebrew Version**: 3.2.11
-   **Node Version**: 14.17.6
-   **NPM Version**: 7.22.0
-   **Operating System**: Darwin Daniels-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

#### Please let me know if more information is needed. Thank you.

**Comment by dmbdesignpdx** [comment]
?

**Comment by andreascful** [comment]
Hello,

I'm sorry for the very long response time. Could you try to update the cli to the newest version and add `--assets-directory [your-assets-folder]` to your command and have a look if this changes the behaviour?

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
