### ISSUE TITLE
429 too many requests

### ISSUE THREAD

**Issue by pierremonico** [contentful/contentful-cli#1143]
## Expected Behavior 

Using `contentful space import` I can import a JSON file.

## Actual Behavior

I get a: 
```
RateLimitExceeded: Status: 429 - Too Many Requests - Message: You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again. - Request ID: <requestid>
```

## Possible Solution

Allow to limit the rate at which the API is called using an option.

## Steps to Reproduce

Works with any JSON file to import that has more than 20 entries. 

## Context

I understand that rate is limited for free plans but there should be a possibility to limit the rate from your CLI, otherwise that would basically mean that free users don't have the opportunity to use the CLI. 

## Environment

Node Version: output of `v14.15.4`
Npm Version: output of `7.6.0`
Operating System: `Big Sur`

**Comment by andreascful** [comment]
Hello,

this message is usually just logged but should not lead to a failure of the import. We do already rate limit the requests and have a retry logic in place. So while you might see this message (when you hit the API limit) it should still succeed when retrying. 
So if this is still an issue could you please confirm whether the import is succeeding or not.

**Comment by tifafracicaAvant** [comment]
I guys I have the same issue, I need to get an asset data and I had this error

**Comment by loolooii** [comment]
I'm getting `Rate limit error occurred. Waiting for 1572 ms before retrying...`, but it just hangs. This happens in `Importing assets` step.

**Comment by jasonsemkohoag** [comment]
@damienxy  still an issue, I get the same issue as @loolooii above, just hangs on the same message and doesn't proceed.

node 22

**Comment by kavand-intive** [comment]
@damienxy @andreascful Getting error after retrying multiple times, even after different time intervals.

```
 ⠋ Importing Assets
      → ⚠ Rate limit error occurred. Waiting for 1628 ms before retrying...
```
      
contentful v3.7.1
node v18.20.4
