### ISSUE TITLE
Support for deleting entries in CLI?

### ISSUE THREAD

**Issue by akkina9** [contentful/contentful-cli#128]
Using CLI, I am able to create/update entries, but I did not see an option to delete entry(s). Is it missing?

**Comment by GLosch** [comment]
@akkina9 did you ever figure this out?

**Comment by phoebeschmidt** [comment]
@akkina9 @GLosch we don't do any entry management (create, update, or delete) from the CLI. 

Do you mean with our management sdk? https://github.com/contentful/contentful-management.js

**Comment by murohima** [comment]
@phoebeschmidt 
We can actually create and update entries from the CLI. But deleting or unpublishing entries is not possible. Is it a feature that will be implemented?

Thanks.

**Comment by phoebeschmidt** [comment]
@murohima Ah I realize maybe you mean using the CLI via a migration script? (That project is called via the CLI https://github.com/contentful/contentful-migration)

That's not planned to be implemented. Unpublishing and deleting is better done by a CMA script using our [management sdk](contentful/contentful-management.js).
