### ISSUE TITLE
`zlib` is deprecated

### ISSUE THREAD

**Issue by romandecker** [contentful/contentful-cli#1331]
## Expected Behavior

contentful-cli does not use any deprecated packages. 

## Actual Behavior

contentful-cli uses [`zlib`](https://github.com/kkaefer/DEPRECATED-node-zlib)

## Possible Solution

zlib functionality is now available in node.js core: https://nodejs.org/dist/latest/docs/api/zlib.html

**Comment by damienxy** [comment]
Hi @romandecker, the `zlib` dependency was removed in version 1.12.5, so I'll close this issue.
