### ISSUE TITLE
Exporting multiple content types 

### ISSUE THREAD

**Issue by jonashilmersson** [contentful/contentful-cli#1389]
I want to export multiple content types in one request.

## Expected Behavior
I use the following configuration for queryEntries:

```json
  "queryEntries": [
   "content_type=productWizardOverview,productWizardStart"
  ],

```
Entries of both types productWizardOverview and productWizardStart should be included.

## Actual Behavior
I get this error.

`11:32:68 - Error: Status: 400 - Bad Request - Message: A Content Type ID is required. When querying for Entries and involving fields you need to limit your query to a specific Content Type. Please send a Content Type ID (not the name) as the URI query parameter "content_type" - Request ID: 4f052b37-0017-4bc1-8aa6-ef5ce04b79e3`

## Environment
Windows 10 21H2 19044.1525
Contentful-cli version : 0.0.0-determined-by-semantic-release
Contentful-cli type: Windows Executable

**Comment by marcolink** [comment]
Hi @jonashilmersson 👋 
Unfortunately, the `content_type` parameter only allows a single content type id.
What should work: 
```
"queryEntries": [
   "content_type=productWizardOverview",
   "content_type=productWizardStart"
],
```
