### ISSUE TITLE
No multiple configs in .contentfulrc.json

### ISSUE THREAD

**Issue by schoenwaldnils** [contentful/contentful-cli#141]
## Expected Behavior

shouldn’t it be possible to add *multiple configs* in the `.contentfulrc.json`?

## Actual Behavior

When i use `contentful config add` it overrides my last config.
`contentful config list` therefore only shows one config.

## Environment

Node Version: v10.9.0
Npm Version: 6.2.0
Package Version: contentful-cli@0.26.6

**Comment by Khaledgarbaya** [comment]
this sounds like a great feature to have.
Something like multiple config profiles

**Comment by makinwab** [comment]
We'll keep this in mind, however, I'll close this for now and add a reconsider label.
