### ISSUE TITLE
List spaces by organization

### ISSUE THREAD

**Issue by y-luis** [contentful/contentful-cli#144]
## Expected Behavior

I would expect to have the posibility to list spaces belonging to a specific organization.

## Actual Behavior

`contentful space list` command does not accept any argument.

## Possible Solution

Add a `--organization_id` argument to `contentful space list` command to list only spaces belonging to the organization with specific ID.

## Environment

-   **Language Version**: v12.1.0
-   **Package Manager Version**: 6.9.0
-   **Browser Version**: Does not apply
-   **Operating System**: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
-   **Package Version**: contentful-cli@0.26.7

**Comment by makinwab** [comment]
This is very useful to have, unfortunately, the API doesn't provide all we need to make this happen.

However, we'll keep this in mind.
