### ISSUE TITLE
contentful login still hangs

### ISSUE THREAD

**Issue by shadowhand** [contentful/contentful-cli#146]
Refs #138 

The problem still exists in 0.27.0. Running `contentful login` doesn't do anything when pasting the token and cannot be killed with ^C.

**Comment by coetry** [comment]
I've also experienced this in 0.28.0. Have had to use the workaround as suggested in #138

**Comment by makinwab** [comment]
A fix for this issue is now available with the new version, **0.29.0**.  

You can re-install the package using `npm install -g contentful-cli@v2.9.0`.
