### ISSUE TITLE
Cannot export specific content types with CLI export

### ISSUE THREAD

**Issue by Raulif** [contentful/contentful-cli#1468]
## Expected Behavior

After running the export query on the CLI, only the Content Types specified in the field `queryEntries`in the config file should be fetched.

## Actual Behavior

After running the export query on the CLI with only 1 Content Type ID specified in the config file, all current 44 Content Types are fetched and stored in the destination file.

## Steps to Reproduce

1. Content of my config file:

```
/* export.config.json */

{
  "spaceId": "xxxxxxxx",
  "environmentId": "staging",
  "managementToken": "CFPAT-f_XXXXXXXXX",
  "exportDir": "./",
  "saveFile": true,
  "contentFile": "export-content.json",
  "skipContent": true,
  "skipContentModel": false,
  "skipRoles": true,
  "skipWebhooks": true,
  "queryEntries": ["content_type=accordionTab"],
  "host": "api.contentful.com",
  "errorLogFile": "./error.log",
  "useVerboseRenderer": true
}
```

2. I run the script with `contentful space export --config export.config.json`
3. The report in the CLI says 44 Content Types have been downloaded. I can find them all in the `export-content.json` file.
4. The same happens if I run the script through a JS file using the `contentful-export` library and exactly the same config object.

## Context

I am trying to export only 1 Content Type from a particular environment (staging), so I can export it afterwards to another environment (master). 

## Environment

-   **Node Version**: 16.13.2
-   **Package Manager Version**: NPM 8.1.2
-   **Operating System**: macOS Big Sur v11.6
-   **Package Version**: "contentful-export" v7.15.0

**Comment by maxoverhere1** [comment]
It would be super useful to be able to export a single content type. We have added a new content type to one space and want an easy way to add it to all our other spaces.
