### ISSUE TITLE
Non pretty command outputs

### ISSUE THREAD

**Issue by ThomasM-E2X** [contentful/contentful-cli#1476]
## Suggestion
Have the ability to output the results of a command in a non "pretty" way

## Context
Im trying to write a script to parse the output of some CLI commands but its really annoying to have to constantly strip back all the formatting on the output

## Expected Behavior
`contentful space accesstoken list` Should print the contents of the command in a simple (non pretty) format

```
name:name
desc:desc
token:<token>
```

## Actual Behavior
Prints the contents in the table form
```
┌────────────────────────────┬──────────────────────────────────────────┬─────────────────────────────────────────────┐
│ Name                       │ Description                              │ Token                                       │
├────────────────────────────┼──────────────────────────────────────────┼─────────────────────────────────────────────┤
│ <name>                     │ <desc>                                   │ <TOKEN>                                     │ 
└────────────────────────────┴──────────────────────────────────────────┴─────────────────────────────────────────────┘
```

## Possible Solution
Add a flag to be switch between pretty and non-pretty outputs? Maybe something like this`--pretty`

**Comment by andreascful** [comment]
This feature has been added to version [1.13.0](https://github.com/contentful/contentful-cli/releases/tag/v1.13.0)
Please update your client to use it.

I'm closing this ticket for now, but feel free to reach out again if you have more questions.
