### ISSUE TITLE
Unable to Modify Content Type Validations on Entry Array

### ISSUE THREAD

**Issue by mlkirkpatrick** [contentful/contentful-cli#148]
I have a field of type "References, many" (an array of entries) with some validations. In Contentful's UI, I've selected some content types that I want to restrict the field to, and this seems to work. However, I am trying to modify the validations with Contentful CLI and it seems we are not able to modify this validation for arrays, even though it clearly is valid. This is the code snippet in my migration:
```
const linkGroup = migration.editContentType('linkGroup')
linkGroup.editField('links')
    .validations([
      { 'linkContentType': ['page', 'internalLink', 'externalLink', 'resource'] }
    ])
```
The error I receive says `Array fields do not support "linkContentType" validations`

When I use the Content Management API to retrieve this content type, I get this:
```
{
    "id": "links",
    "name": "Links",
    "type": "Array",
    "localized": false,
    "required": false,
    "validations": [],
    "disabled": false,
    "omitted": false,
    "items": {
        "type": "Link",
        "validations": [
            {
                "linkContentType": [
                    "externalLink",
                    "internalLink",
                    "page"
                ]
            }
        ],
        "linkType": "Entry"
    }
},
```

This seems to be a discrepancy between what the CLI allows and what is actually valid.

**Comment by phoebeschmidt** [comment]
hey @mlkirkpatrick sorry to be bureaucratic but do you mind moving this ticket over to https://github.com/contentful/contentful-migration? easier for us to track that way. Thanks so much!

**Comment by makinwab** [comment]
Re: https://github.com/contentful/contentful-migration/issues/313
Moving issue over to contentful-migration.

**Comment by TimBeyer** [comment]
@mlkirkpatrick  I think the problem here is that you're writing to the `validations` property, but this is only valid on `items.validations`.

So it needs to be something like 

```js
const linkGroup = migration.editContentType('linkGroup')
linkGroup.editField('links').items({
  validations: [
    { 'linkContentType': ['page', 'internalLink', 'externalLink', 'resource'] }
  ]
})
```
