### ISSUE TITLE
contentful boilerplate complains about missing accesToken

### ISSUE THREAD

**Issue by joao-parana** [contentful/contentful-cli#168]
## Expected Behavior

The Java boilerplate generated

## Actual Behavior

```bash

? Which boilerplate would you like to get? Contentful Java boilerplate
  ✖ Creating CDA access token
    → Expected parameter accessToken
    Downloading Contentful Java boilerplate boilerplate
    Writing files to disk
🚨  Error: Expected parameter accessToken
┌─────────────────────────────────────────────────────────────────────────┐
│ TypeError: Expected parameter accessToken                               │
│      at createClient                                                    │
│ (/usr/local/lib/node_modules/contentful-cli/node_modules/contentful-ma… │
│      at createManagementClient                                          │
│ (/usr/local/lib/node_modules/contentful-cli/dist/utils/contentful-clie… │
│      at process._tickCallback (internal/process/next_tick.js:68:7)      │
└─────────────────────────────────────────────────────────────────────────┘
```

## Steps to Reproduce

1. Execute this on Terminal

```bash
contentful login
contentful space use
contentful boilerplate
```

2. Choose Java

3. See the error

## Environment

Node Version: v10.16.2
Npm Version: 6.10.3
Operating System: Mac OS 10.14.6 - Darwin MacBook-Air.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
Package Version:
```bash
npm list contentful-cli
contentful-starter-gatsby-blog@0.0.1 /Users/admin/Desktop/Development/EIC/starter-gatsby-blog
└── (empty)
```

-   **Language Version**:
-   **Package Manager Version**:
-   **Browser Version**: Safari 12.1.2
-   **Operating System**: Mac OS 10.14.6
-   **Package Version**:

**Comment by swadhera** [comment]
Facing the same issue , is there any solution for this , tried the below steps for creating JavaScript boilerplate.

contentful login
contentful space use
contentful boilerplate
