### ISSUE TITLE
Active? How Active is this project at contentful?

### ISSUE THREAD

**Issue by scottpopplewell** [contentful/contentful-cli#1680]
I'd love to see if we could add commands for managing actual content or is that outside the scope of this cli tool?

**Comment by domilejanenaite** [comment]
Hi Scott, 

I am a Product Manager at Contentful and am curious to learn more about your use case. What are you trying to achieve and what do your workflows look like currently? 

Best,
Domi

**Comment by denkristoffer** [comment]
I will close this ticket but feel free to re-open to address the questions from Domi 🙂
