### ISSUE TITLE
Unable to import (422)

### ISSUE THREAD

**Issue by baumars** [contentful/contentful-cli#171]
## Expected Behavior

I would like to export an entry 'testtitre_aq' from 'developmentSA' env : 

![Capture1](https://user-images.githubusercontent.com/50198902/63422660-1a832f00-c40b-11e9-98d9-f8de247fff3e.PNG)

The entry is exported in the JSON generated file : 

![Capture](https://user-images.githubusercontent.com/50198902/63422869-79e13f00-c40b-11e9-890d-0cb471fb7128.PNG)

The import into another env 'devtest' should work.

## Actual Behavior

![Capture2](https://user-images.githubusercontent.com/50198902/63423130-ee1be280-c40b-11e9-918e-59fee906e29d.PNG)

## Possible Solution
Bug ??

## Steps to Reproduce

1. contentful login (OAuth via browser token)
2. contentful space export --environment-id 'developmentSA' --query-entries 'sys.id=6uhYB6FxV1TIzxAJSkkuvk'
3. contentful space import --environment-id 'devtest' --content-file contentful-export-<space_id>-developmentSA-2019-08-21T11-15-89.json

## Environment

Node : v10.16.3
Npm  : 6.9.0
OS   : Windows 10 - 64 bits

Contentful-CLI : 0.36.2

**Comment by Khaledgarbaya** [comment]
Hi @baumars,
this happened because you exported only the entry with the id `6uhYB6FxV1TIzxAJSkkuvk` and that entry had references so when importing the API will throw an error because the reference entry does not exist.

you could do something like `contentful space export --environment-id 'developmentSA' --query-entries 'sys.id[in]=6uhYB6FxV1TIzxAJSkkuvk,ref_id'`

**Comment by baumars** [comment]
Hi @Khaledgarbaya,

I did as per your suggestions, but still not working : 

`contentful space export --environment-id 'developmentSA' --query-entries 'sys.id[in]=6uhYB6FxV1TIzxAJSkkuvk,ref_id'`

`contentful space import --environment-id 'devtest' --content-file contentful-export-<space_id>-developmentSA-2019-08-21T14-32-86.json`

![Capture111](https://user-images.githubusercontent.com/50198902/63434961-55df2700-c426-11e9-9ec7-35e848ec1821.PNG)

**Comment by Khaledgarbaya** [comment]
> contentful space export --environment-id 'developmentSA' --query-entries 'sys.id[in]=6uhYB6FxV1TIzxAJSkkuvk,ref_id'

`ref_id` was just an example it should be the actual id of the referenced entry

**Comment by baumars** [comment]
Where to find that 'actual id of the referenced entry' ?

![Capture111](https://user-images.githubusercontent.com/50198902/63439824-10732780-c42f-11e9-9443-c191e85ee971.PNG)

**Comment by Khaledgarbaya** [comment]
> Where to find that 'actual id of the referenced entry' ?
Yes

**Comment by baumars** [comment]
Not sure if I understand your answer. Is the 'actual id of the referenced entry' the same as the 'entry id' as shown in the image above ?

**Comment by phoebeschmidt** [comment]
@baumars 
> Is the 'actual id of the referenced entry' the same as the 'entry id' as shown in the image above ?

yes exactly

**Comment by baumars** [comment]
Unfortunately still not working ...

`contentful space export --environment-id 'developmentSA' --query-entries 'sys.id[in]=6uhYB6FxV1TIzxAJSkkuvk'`

`contentful space import --environment-id 'devtest' --content-file contentful-export-<space-id>-developmentSA-2019-08-21T16-50-12.json`

![Capture111](https://user-images.githubusercontent.com/50198902/63445930-8f6d5d80-c439-11e9-829c-9eb51c04228a.PNG)

**Comment by baumars** [comment]
Anyone ?

**Comment by Khaledgarbaya** [comment]
Hi @baumars,
Sorry for the confusion.
Let's say you have an entry with an id `xxxx` that reference and entry that has an id `yyyy`. If you want to only export and import them you need to include both their ids in the `query-entries` parameter.

Like this
`contentful space export --environment-id 'developmentSA' --query-entries 'sys.id[in]=xxxx,yyyy'`.

You need to replace the `xxxx` and `yyyy` with the real IDs.

If your entry also references an asset make sure to include its ID also.

Cheers,
Khaled

**Comment by baumars** [comment]
Hi @Khaledgarbaya ,

If I understand correctly, the `yyyy` refers to 'ENTRY ID' as shown in the screenshot above, which is `6uhYB6FxV1TIzxAJSkkuvk`.

What about the `xxxx` , where to find its value as per the screenshot ?

**Comment by baumars** [comment]
Anyone please ?

**Comment by phoebeschmidt** [comment]
Hi @baumars,

the `xxxx` that Khaled was referring to is the entry ID of every linked entry. So in the Contentful web app, you'll have to go to the entry you're looking to export, `6uhYB6FxV1TIzxAJSkkuvk`, scroll through and find any other entries linked from there, and then manually copy the id for each of those entries.

Does that make sense?

**Comment by baumars** [comment]
Hi @phoebeschmidt , 

Unfortunately, it doesn't make sense to me ... so here is the screen shot :  

![Capture](https://user-images.githubusercontent.com/50198902/63580788-d6706580-c595-11e9-8642-f825400b4376.PNG)


In that screenshot, all I have is just the ENTRY_ID or `yyyy`, but where is the `xxxx` ?

**Comment by phoebeschmidt** [comment]
@baumars is that the entire entry? there are no other fields pointing at other entries?

could you please attach a copy of your error log file to us? (one is generated when the export fails). thank you!

**Comment by baumars** [comment]
@phoebeschmidt ,

Yes, that's the enitre entry, it is just a standalone entry. The error log is when importing, not when exporting ...

[contentful-import-error-log-ef04tndlnzev-2019-08-21T16-51-74.log](https://github.com/contentful/contentful-cli/files/3533832/contentful-import-error-log-ef04tndlnzev-2019-08-21T16-51-74.log)

**Comment by phoebeschmidt** [comment]
@baumars 

You're correct, I was mistaken before, I meant the error from importing.

This error log is huge, I'm assuming it's from when you tried to import a JSON file for the entire space, not just the one entry?

Either way, inspecting that file it seems you are receiving many 403: Access Denied errors. You don't have permissions to create content types, that's why it's failing when you attempt to import.

You should confirm your role and check with your space admin to fix this problem.

And in the future, if you look at the error log it will provide much more detailed information about the errors than the summary output to your command line.

I hope this helped.

**Comment by baumars** [comment]
Hi @phoebeschmidt ,

I am already connecting as an admin when executing the CLI : 

![image](https://user-images.githubusercontent.com/50198902/63586138-f48f9300-c5a0-11e9-8fda-58770df804ef.png)

![image](https://user-images.githubusercontent.com/50198902/63586414-8ac3b900-c5a1-11e9-85aa-7394738ed8de.png)


What else I need to verify ?

**Comment by phoebeschmidt** [comment]
@baumars I am simply reading and trying to understand your error log. Is it the most recent error log? Have you been importing into one of these spaces where you are an admin? Are you using a management_token from this account when you try to do you import?

**Comment by baumars** [comment]
@phoebeschmidt ,

 Is it the most recent error log?
> Yes, that's the latest

Have you been importing into one of these spaces where you are an admin?
> No, this is the first time ever we try to perform export - import from any sandbox

Are you using a management_token from this account when you try to do you import?
> I run the CLI from Windows prompt : 
> `contentful login` then from my browser, I login using my admin account (ba1012info@gmail.com) to get the token, then paste it

**Comment by phoebeschmidt** [comment]
@baumars looking into the error log again, I see your access was denied because your usage is exceeded. It seems your target space (the one you are importing to), has reached the limits for content types. 

Here are details about the limits for the different types of spaces: https://www.contentful.com/pricing/

Again, I encourage you to take a look at the error log, as all the information about the errors is contained there.

**Comment by baumars** [comment]
Hi @phoebeschmidt,  

You're right, that the sandbox devtest has already reached the limit (48). So exporting from developmentSA (nb of content type is 41) to devtest failed.

BUT, I reversed the process.

Using the same token as before, I export from devtest (48) then import into developmentSA (41). What strange to me, after looking into the log generated, was the same error message 403 Acces Denied : 

[contentful-import-error-log-ef04tndlnzev-2019-08-23T15-17-89.log](https://github.com/contentful/contentful-cli/files/3534818/contentful-import-error-log-ef04tndlnzev-2019-08-23T15-17-89.log)

**Comment by phoebeschmidt** [comment]
@baumars trying to import 48 content types into a space that only has space for 7 more content types will also cause errors that you've exceeded your limits :)

**Comment by baumars** [comment]
There is a misunderstanding there as I don't import all 48 content types (CT)

I run the command to export just ONE entry of **an existing content type** , not a new one, as before, i.e. `contentful space export --environment-id 'devtest' --query-entries 'sys.id[in]=xxxx'`

The sandbox devtest has 48 CT.

I then import that new entry into developmentSA sandbox, which has 41 CT.

Basically, all I did was just export a new entry of an existing CT into a sandbox which still has room for more CT.

**Comment by phoebeschmidt** [comment]
Can you please inspect the exported json that you are attempting to import? (to confirm that it really is just the one entry being imported).

Looking at your error log, many errors are coming from requests to edit content types. For example, here is a snippet from an error at the end of the log:

```
"data": {
        "status": 403,
        "statusText": "Forbidden",
        "message": "Forbidden",
        "details": {
          "reasons": [
            "usageExceeded",
            "You do not have permissions to create on ContentType, please contact your administrator for more information."
          ]
        },
        "request": {
          "url": "https://api.contentful.com:443/spaces/ef04tndlnzev/environments/developmentSA/content_types/fichePratique",
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/vnd.contentful.management.v1+json",
            "X-Contentful-User-Agent": "app contentful.cli/0.36.2; feature space-import; sdk contentful-management.js/5.2.1; platform node.js/v10.16.3; os Windows/10.0.18362;",
            "Authorization": "Bearer ...TlYZk",
            "user-agent": "node.js/v10.16.3",
            "Accept-Encoding": "gzip",
            "Content-Length": 1577
          },
          "method": "put",
          "payloadData": "{\"displayField\":\"pageId\",\"name\":\"Fiche pratique\",\"description\":\"\",\"fields\":[{\"id\":\"pageId\",\"name\":\"page_id\",\"type\":\"Symbol\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false},{\"id\":\"slug\",\"name\":\"slug\",\"type\":\"Symbol\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false},{\"id\":\"header\",\"name\":\"header\",\"type\":\"Link\",\"localized\":false,\"required\":false,\"validations\":[{\"linkContentType\":[\"pageHeaderPrimary\"]}],\"disabled\":false,\"omitted\":false,\"linkType\":\"Entry\"},{\"id\":\"fiche\",\"name\":\"Fiche\",\"type\":\"RichText\",\"localized\":false,\"required\":false,\"validations\":[{\"nodes\":{}}],\"disabled\":false,\"omitted\":false},{\"id\":\"ficheIncontournable\",\"name\":\"Fiche \\\"incontournable\\\" ?\",\"type\":\"Boolean\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false},{\"id\":\"filtreEtapes\",\"name\":\"Filtre \\\"Etapes\\\"\",\"type\":\"Array\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false,\"items\":{\"type\":\"Link\",\"validations\":[{\"linkContentType\":[\"filtres\"]}],\"linkType\":\"Entry\"}},{\"id\":\"filtreThmatiques\",\"name\":\"Filtre \\\"Thématiques\\\"\",\"type\":\"Array\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false,\"items\":{\"type\":\"Link\",\"validations\":[{\"linkContentType\":[\"filtres\"]}],\"linkType\":\"Entry\"}},{\"id\":\"filtreSecteurs\",\"name\":\"Filtre \\\"Secteurs\\\"\",\"type\":\"Array\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false,\"items\":{\"type\":\"Link\",\"validations\":[{\"linkContentType\":[\"filtres\"]}],\"linkType\":\"Entry\"}}]}"
        },
        "requestId": "95e4fe20d4c73175800449490d232f68"
      }
    }
  }

```

You can see that this error resulted from a PUT to 	`https://api.contentful.com:443/spaces/ef04tndlnzev/environments/developmentSA/content_types/fichePratique`. If you are doing as you intend, only importing one entry, then this request should not have happened.

**Comment by baumars** [comment]
Hi @phoebeschmidt ,

... only importing one entry ...
> But how ? What is the syntax ?

So far, the process I followed were : 
- `contentful space export --environment-id 'devtest' --query-entries 'sys.id[in]=xxxx'`
But, this will not just export only one entry, there are a lot of others data as well : 

[contentful-export-ef04tndlnzev-devtest-2019-08-23T15-15-14.log](https://github.com/contentful/contentful-cli/files/3540066/contentful-export-ef04tndlnzev-devtest-2019-08-23T15-15-14.log)

- `contentful space import --environment-id 'developmentSA' --content-file <exported_JSON>`
According to the doc, I don't see any parameters to import JUST one entry.

**Comment by phoebeschmidt** [comment]
Hi Baumars,

My understanding is the following:

> your goal is to export and re-import only entry

1. `contentful space export --environment-id 'devtest' --query-entries 'sys.id[in]=xxxx'` 
This command will create a JSON file with the following format:
```
{
  "contentTypes": [],
  "entries": [],
  "assets": [],
  "locales": [],
  "webhooks": [],
  "roles": [],
  "editorInterfaces": []
}
```
(this information is in our README, btw).

You can check this exported json file for which of your contents were actually exported. Specifically, check the `entries` array to see if your `--query-entries` flag successfully found just a single entry to import.

If you don't want to import assets, content_types, webhooks, roles, etc, you can remove those arrays from the JSON file.

2. Then you call import with the modified file. This will attempt to run an import of only that data.

**Important**
If you want to only import one entry, the space must already have the relevant content type (that is, the content type of the entry you want to import).

I hope this clears up some of your misunderstanding. I would also like to point you to some helpful resources:

guide for import/export using cli: https://www.contentful.com/developers/docs/tutorials/cli/import-and-export/
contentful import https://github.com/contentful/contentful-import
contentful export https://github.com/contentful/contentful-export

**Comment by baumars** [comment]
Hi @phoebeschmidt ,

Finally ... 

So here is my scenario. In my sandbox `devtest`, I created a new entry associated with an `existing` content type(CT), then exported using the export CLI : 

`contentful space export --environment-id 'devtest' --query-entries 'sys.id[in]=2ZzuXC4ZDC0udbn6Fijbgp' --content-only`

It is important to specify `content-only`. This will export just one entry, but will a bunch of Assets.

![image](https://user-images.githubusercontent.com/50198902/63778796-cdf59300-c8e5-11e9-8eea-823438ec1d81.png)

When importing, it is important to note that the CT `MUST` exists in the importing sandbox.

You can close this ticket, but I have other question in another ticket.

Thanks @Khaledgarbaya & @phoebeschmidt
