### ISSUE TITLE
Syntax for queries

### ISSUE THREAD

**Issue by baumars** [contentful/contentful-cli#173]
I would like to export entries based on some criterias, such created_date, creted_by, updated, or updated_by, something like this 

`contentful space export --environment-id 'devtest' --query-entries 'created >= dd/mm/yyyy and created_by = John Doe'`

Is it possible ?

**Comment by baumars** [comment]
Anyone please ?

**Comment by phoebeschmidt** [comment]
Hi @baumars, please refer to the readme for our export tool: 

https://github.com/contentful/contentful-export#querying

There is also a link to our API documentation which explains which types of queries we allow. You will find there that range queries (less than, greater than, etc) are available for dates, as well as inclusion on a field for querying specific authors as you suggested above.

You can include multiple filter strings to the `--query-entries` CLI param like so:

```
contentful space export --space-id <space_id>= --management-token <cma_token>  --skip-content-model true --skip-webhooks true --query-entries 'sys.createdBy.sys.id[nin]=2KAvT7gLBcrYJLFYXRsrPUasdf' 'sys.contentType.sys.id[in]=blogPost'
```

And lastly, as a point of politeness, we kindly ask your patience in our responding to your github issues. In the future could you please avoid sending follow up messages asking if anyone is here? We have lots of open source projects to maintain here at Contentful :)  Thanks tons for your understanding.

**Comment by jon-lane-valtech** [comment]
@phoebeschmidt using --query-entries like you showed in your example does not filter out Content Types, it still returns ALL content types for me

**Comment by srigar** [comment]
+1 

```
contentfulExport({
    spaceId: '123123',
    managementToken: 'CFPAT-K4prDHQuMXXXXXXXXXXXXXXXXXXXXXXXXXI',
    environmentId: 'master', // from environment
    queryEntries: ['content_type=migrationTest'] 
}).then((result) => {
    console.log('Your space data:', JSON.stringify(result));
});
```
Above returning all content models other than `migrationTest`
