### ISSUE TITLE
Error when using version 1.19

### ISSUE THREAD

**Issue by juanibiapina** [contentful/contentful-cli#1795]
After upgrading to version 1.19.0 of contentful-cli (`npm install -g contentful-cli`) and trying to run it, I get this error:

```
Error: Cannot find module '../output/lib/cli.js'
Require stack:
- /home/user/resources/node_modules/lib/node_modules/contentful-cli/bin/contentful.js
```

Previously this line used to refer to `../lib/cli.js` in 1.18.0.

The change is made here: https://github.com/contentful/contentful-cli/compare/v1.18.0...v1.19.0#diff-3599c2e1a425af471ac5280a0afbadb5971066c0d2da6632f6fef45fdd9cbd39L3

**Comment by mayakarabula** [comment]
fixed now, thank you for reporting
