### ISSUE TITLE
Generated migration contains deprecated changeEditorInterface method

### ISSUE THREAD

**Issue by stevethatcodes** [contentful/contentful-cli#180]
## Expected Behavior

When generating a migration for a space via the following command: `contentful space generate migration -s {space} -e {env} -f 001-initial-migration.js`, the generated code does not contain deprecated method calls.

## Actual Behavior

The following warning is logged for each Content Type being created via the migration: `(deprecated) Method changeEditorInterface is deprecated and will be removed, use changeFieldControl instead`

## Possible Solution

* Alter generated code to use the suggested `changeFieldControl` method.

## Steps to Reproduce

1. Create a space with a simple content type
2. Use contentful-cli to generate a migration for that space
3. Run the migration against another space or environment

## Context

Although just a deprecation warning, this lowers confidence that migrations generated using the CLI will continue to work without being regenerated in the future or manually updated.

## Environment

-   **Language Version**: Node v10.16.2
-   **Package Manager Version**: NPM 6.9.0
-   **Browser Version**: n/a
-   **Operating System**: Mac OS 10.14.6
-   **Package Version**: 1.1.0

**Comment by jroehl** [comment]
Resolved by #181 - part of CLI version 1.1.1
