### ISSUE TITLE
Audit reports dependency issue - https-proxy-agent

### ISSUE THREAD

**Issue by peacq** [contentful/contentful-cli#183]
When we run npm audit we are seeing an issue with https-proxy-agent which needs to be upgraded to 3.0.0 or greater. This is causing our CI pipelines to fail.
https://www.npmjs.com/advisories/1184

**Comment by jroehl** [comment]
The `dev-dependencies` (`semantic-release` and `codecov`) might still show the audit warning, relying themselves on an earlier version of `https-proxy-agent`. As they are only `dev-dependencies` this is no risk for production builds.

As soon as the dependency owners updated their packages, we will update our package again.
