### ISSUE TITLE
Re-export contentfful-migration types

### ISSUE THREAD

**Issue by jordanrastrick** [contentful/contentful-cli#189]
## Expected Behavior

It would be a nice feature if `contentful-cli` re-exported the `MigrationFunction` type from the `contentful-migration` package. 

## Context

At the moment we use `contentful-cli` to actually run our migrations (as well as other related tasks like uploading UI Extensions), but to typecheck the migration scripts we have to get the `MigrationFunction` type from a separate dependency on `contentful-migration`. This requires manual management of the versions of the `contentful-migration` dependency and sub-dependency to ensure they don't drift and cause types to become mismatched from implementation (which seemed to happen recently with changes to the signature of `changeFieldControl`). Ideally we would eliminate the top level dependency on `contentful-migration` altogether to avoid the problem.

**Comment by makinwab** [comment]
Hi @jordanrastrick, your request is quite understandable. We'll keep this in mind, however, in the meantime you'll still have to carry on installing the underlying library.

I'll close this for now and add a reconsider label to this.
