### ISSUE TITLE
Calling `contentful completion` Instead Renders the Show Help Text.

### ISSUE THREAD

**Issue by hyprhare** [contentful/contentful-cli#19]
## Expected Behavior

I'm expecting a bash script as output, yes?

## Actual Behavior
```
Usage: contentful <cmd> [args]

Commands:
  completion    generate bash completion script
  boilerplate   Download a boilerplate
  config        Manage and list your configs
  content-type  Manage and list your space content types           [aliases: ct]
  extension     Manage and list your extensions
  guide         A guide introducing basic concepts of working with Contentful
  login         Login to Contentful
  logout        Logout from Contentful
  space         Manage and list your spaces

Options:
  -h, --help     Show help                                             [boolean]
  -v, --version  Show current version                                  [boolean]

Copyright 2018 Contentful, this is a BETA release

Please specify a command.
```

## Possible Solution

Add `completion` as a match-able input.

## Steps to Reproduce

1. contentful completion

## Context

Just ran the following commands before hand...
1. sudo npm install -g contentful-cli
2. contentful login
3. npm install

## Environment

node: v6.11.4
npm: 3.5.2
contentful-cli: 0.8.3
Operating System: Ubuntu 17.10

**Comment by ristomatti** [comment]
There seems to be just a stub for this command with no implementation. I would suggest removing references to the command from README.md and from code.
