### ISSUE TITLE
space export: "rawProxy" and "includeArchived" options not working in configuration file 

### ISSUE THREAD

**Issue by rustyy** [contentful/contentful-cli#194]
Hi,
I just wondered whether the options "raw-proxy" and "include-archived" are missing for the export command.
They seem not available through help command but are working if passed as option but don't if provided by config.json in camel-case-style.

Wouldn't it be better having them documented as well as being able to use them camel-cased like all the other options in a configuration file?

## Expected Behavior

- executing ```contentful space export --help``` shows options "raw-proxy" and "include-archived"
- Options "raw-proxy" and "include-archived" can be used camel-case style in configuration-file

    In config.json

        {
            "rawProxy": true,
            "includeArchived": true
            ...
        }

    and are passed to 'contentful-export' and are executed.

## Actual Behavior

- options are not shown using ```contentful space export --help```
- when used in configuration-file and camel-cased, CLI aborts with unknown argument error

    unknown argument: rawProxy
    unknown argument: includeArchived

## Possible Solution

Add options to builder-function in [https://github.com/contentful/contentful-cli/blob/master/lib/cmds/space_cmds/export.js]() seems to solve the issue.

    module.exports.builder = function(yargs) {
        return yargs
            ...
            .option('include-archived', {
              describe: 'Include archived entries in the exported entries',
              type: 'boolean',
              default: false
            })
            .option('raw-proxy', {
              describe:
                'Pass proxy config to Axios instead of creating a custom httpsAgent',
              type: 'boolean'
            })
            ...

## Steps to Reproduce

- Create a config.json

        {
            "rawProxy": true,
            "includeArchived": true
        }
        
-   execute ```contentful space export --config config.json```

## Environment

-   **Node Version**: v10.16.3
-   **Package Manager Version**: npm 6.12.1
-   **Operating System**: macOS 10.15.1
-   **Package Version**: 0.36.2

**Comment by makinwab** [comment]
Thanks for bringing this to our attention. 
These options are now available in the new CLI version **v1.3.0.**
