### ISSUE TITLE
Error when trying to list extensions for space environment when Apps are installed

### ISSUE THREAD

**Issue by cyberpantz** [contentful/contentful-cli#197]
## Expected Behavior

I've installed the Cloudinary and Dropbox Apps in my 'stage' space via the Contentful webapp. I expected extension information from contentful-cli to return in list without errors, but the apps are also being returned by the **extension** **get** and **list** commands, even though they are not properly formed extensions. This is causing a null pointer exception.

## Actual Behavior
After running `extensions list` command:
`contentful extension --space-id=SPACE_ID --environment-id=stage list`

I am getting the following:
`TypeError: Cannot read property 'name' of undefined                                                                                                                   
│      at /usr/local/lib/node_modules/contentful-cli/lib/cmds/extension_cmds/list.js:45:19   `

It seems that Apps installed in an environment are returned via the extensions api, but are not properly formed extensions.

## Possible Solution

Error is happening because a.extension does not exist. 
`
  if (result.items.length) {
    const extensions = result.items.sort((a, b) =>
      a.extension.name.localeCompare(b.extension.name)
    )
`

It looks like there is no check to make sure extension object is valid before trying to access name property on it. 

Either: 

1) Do not return 'apps' via the extensions get/list commands, or
2) Ensure that Apps are properly formed extensions
3) Wrap code to retrieve extension info in null pointer safety check

## Steps to Reproduce

1. Create new space environment in webapp
2. Add one or more Apps (in the Apps tab in contentful webapp) to a space environment.
3. Run either the  'list' or get 'get' extension commands 
4. Null pointer exception happens...

Note: This might be because the 'extensions' I installed were actually installed in the Apps tab of the contentful webapp. Maybe installing Apps there does not add correct info?

I am able to see the Cloudinary and Dropbox apps just fine when I hit the extensions API using cURL.

## Environment
Node Version: `v12.13.0`
Npm Version: `6.12.0`
contentful-cli Version: `1.1.5`

**Comment by makinwab** [comment]
@cyberpantz, it seems this issue is now resolved. I don't see the apps being returned alongside the extensions.

I'll be closing this issue, let me know if you're still facing this and we can reopen.
