### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by radmen** [contentful/contentful-cli#198]
Hello,

I just wanted to let you know, that I've created an AUR package for Arch-based Linux distros.

You can find it here: https://aur.archlinux.org/packages/nodejs-contentful-cli/

To install:

```
yay -S nodejs-contentful-cli
```

This is just an FYI, you can do with it whatever you want :)

**Comment by phoebeschmidt** [comment]
Hey @radmen, cool! Thanks so much! I'll close the issue but now it should be discoverable for interested folks.
