### ISSUE TITLE
`merge show` and `merge export` commands result in `PollTimeout` error

### ISSUE THREAD

**Issue by eric-schmidt** [contentful/contentful-cli#1984]
## Expected Behavior

Running `contentful merge show` or `contentful merge export` should result in success (either showing the merge diff if the former, and actually running the merge if the latter).

## Actual Behavior

When running both commands above, when Contentful CLI is installed either via Homebrew or NPM, a `PollTimeout` error is encountered.

## Steps to Reproduce

1. Ensure you are running an up-to-date version of this package, either via NPM or Homebrew (i.e. >= 2.3.0).
2. Run either `contentful merge show --space-id <YOUR SPACE ID> --te <YOUR TARGET ENVIRONMENT> --se <YOUR SOURCE ENVIRONMENT>` or `contentful merge export --space-id <YOUR SPACE ID> --te <YOUR TARGET ENVIRONMENT> --se <YOUR SOURCE ENVIRONMENT>`.
3. Note the following error:
<img width="900" alt="Screenshot 2023-04-13 at 12 32 38 PM" src="https://user-images.githubusercontent.com/913312/231861012-a80cb045-46f1-40ea-94c4-f0d59669d2c4.png">

## Environment

-   **Language Version**:
    - Node version: 16.15.1
-   **Package Manager Version**:
    - NPM version: 8.11.0
-   **Operating System**:
    - OSX 13.2.1
-   **Package Version**:
    - 2.3.x

**Comment by nswitzer** [comment]
I can confirm I'm seeing the same behavior as @eric-schmidt here. Screenshot of the output from both commands:
<img width="1165" alt="Screenshot 2023-04-13 at 4 51 07 PM" src="https://user-images.githubusercontent.com/1634837/231899884-a70aa46e-2f47-432e-953b-04b50f6a40a1.png">

### Environment

- **Language version:**
  - Node version: 18.12.1
- **Package Manager Version:**
  - NPM version: 8.19.2
- **Operating System:**
  - Mac OS 13.2.1
- **Package Version:**
  - 2.3.x

**Comment by crissto** [comment]
Hello @eric-schmidt and @nswitzer thanks for the input. We made errors nicer and also fixed the underlying bug that you reported. 
Going from version `2.4.0` the new `merge show` and `merge export` commands should work as expected.

**Comment by marcolink** [comment]
This has been fixed! 
closing the issue for now.
