### ISSUE TITLE
No possiblity to modify accesstokens

### ISSUE THREAD

**Issue by Wouter-Delellio** [contentful/contentful-cli#208]
## Expected Behavior
I would like to be able to modify an accesstoken from the CLI.

## Actual Behavior
Currently, it is possible to create new environments from the CLI as documented [here](https://www.contentful.com/developers/docs/tutorials/cli/environment-management/)
But after creating them, a manual intervention is still required to activate the accesstoken for that new environment.
It would be nice if this could also be added as an option in the CLI. Right now we can list and create accesstokens, but not modify existing ones.

## Context
I'm trying to create a bash script that will automate the creation of a new environment and would result in having the new environment accessible through my existing accesstoken.

## Environment
Running on contentful-cli 1.1.1

**Comment by Vasant-Patel** [comment]
We also have similar use-case and it would be very helpful if there was a way to deal with existing token especially assigning access to the api key to newly created environments

**Comment by marcolink** [comment]
Hi @Wouter-Delellio,
Hi @Vasant-Patel,

While this is currently not possible with `contentful-cli`,  I recommend the [Content Management SDK](https://github.com/contentful/contentful-management.js/), 
to create [API keys](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/api-keys/delivery-api-keys-collection/create-a-delivery-api-key/console/js).

I will close this issue for now. Feel free to open it again.
