### ISSUE TITLE
Unable to create extensions with `src` via contentful-cli extension

### ISSUE THREAD

**Issue by brettinternet** [contentful/contentful-cli#217]
The following command produces an error:

```
contentful extension create --id ${EXTENSION_ID} --space-id ${SPACE_ID} --name ${EXTENSION_NAME} --management-Token ${CONTENTFUL_MANAGEMENT_ACCESS_TOKEN} --field-types Object --src ${EXTENSION_SRC}"
```
Where `EXTENSION_SRC=https://<my hosted extension>.com/index.html`.

#### Error:

```
Error: Validation error
Does not match /(^https://)|(^http://localhost(:[0-9]+)?(/|$))/ at extension/src
```

```
"status": 422,                                                        
    "statusText": "Unprocessable Entity",                             
    "message": "Validation error",                                    
    "details": {                                                      
      "errors": [                                                     
        {                                                             
          "name": "regexp",                                           
          "details": "Does not match                                  
 /(^https://)|(^http://localhost(:[0-9]+)?(/|$))/",                   
          "path": [                                                   
            "extension",                                              
            "src"                                                     
          ],                                                          
          "value": "",                                                
          "pattern": "(^https://)|(^http://localhost(:[0-9]+)?(/|$))" 
        }                                                             
      ]                                                               
    },     
```

## Expected Behavior

URLs like `https://<my hosted extension>.com/index.html` should be allowed.

## Actual Behavior

These URLs are rejected.

My workaround is to manually add this URL (yes, the exact same URL) into the Contentful Extensions console.

## Possible Solution

The regex (`/(^https://)|(^http://localhost(:[0-9]+)?(/|$))/`) probably needs to escape forward-slashes: `/(^https:\/\/)|(^http:\/\/localhost(:[0-9]+)?(\/|$))/`

## Environment

Node Version: `v13.7.0`
Npm Version: `6.13.6`
Operating System: GNU/Linux
Package Version: `1.2.11`

**Comment by jelz** [comment]
Hi @brettinternet 

I've just tested the API and it persisted `https://test.com/index.html`.

`pattern` in the error response you're getting omits escape characters for readability.

I don't know what's your shell but I'd recommend trying `--src "${EXTENSION_SRC}"` (double quotes around var interpolation).

**Comment by brettinternet** [comment]
@jelz You're absolutely right. Thank you for the recommendation.
