### ISSUE TITLE
Does the import tool import downloaded assets from the export tool? 

### ISSUE THREAD

**Issue by pouriaalmassi** [contentful/contentful-cli#225]
## Context

I would like to mirror one of my organization's environments to another to sync content. If I have read and understood the [commands for a space](https://github.com/contentful/contentful-cli/tree/master/docs/space) there is no command to sync environments. However, we have considered using the export and import commands to accomplish this. Is this a viable option? One gap we have noticed in the import tool is that there is no mention of importing assets downloaded from the export tool. Perhaps because we are using the CLI tool in an unintended way. 

- Is it event possible to sync environments? 
- How to import assets into Contentful that have been exported from Contentful?

- [Export docs](https://github.com/contentful/contentful-cli/tree/master/docs/space/export) -- specifically note the option to download assets by including `--download-assets`. 
- [Import docs](https://github.com/contentful/contentful-cli/tree/master/docs/space/import) -- note the absense of any flag related to assets.

## Environment

-   **Language Version**: Node version 13.8.0
-   **Package Manager Version**: npm version 6.13.7
-   **Browser Version**: NA
-   **Operating System**: Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
-   **Package Version**: contentful-cli version 1.2.12

**Comment by makinwab** [comment]
Hi @pouriaalmassi, if by sync environment, you mean you want to have the content in one environment copied to another environment, yes, this is possible.

- You can export content (which includes assets) from an environment in a given space with: 
```
contentful space export --space-id SPACE-ID --environment-id ENVIRONMENT-ID 
```

The option `--download-assets` is for cases where you want to download the asset files to your local machine. 
Based on what I understand you want, you don't need this option.

- You can import the exported content (which includes your assets) to an environment in a given space like so:
```
contentful space import --space-id SPACE-ID --environment-id ENVIRONMENT-ID --content-file EXPORTED-FILE
```
This would successfully import the assets as well as other entities into the specified environment.

I hope this was helpful. If you have more questions regarding import, please feel free to ask in the [slack community](https://www.contentful.com/slack/) or create a new issue in the [contentful-import repo](https://github.com/contentful/contentful-import/issues)

**Comment by dsevans93** [comment]
For clarity's sake, the reason that you don't need to download assets when exporting and importing into the same space is that the files for an asset are stored as urls in the asset export json, and the files pointed to by those urls will be available to all environments in that space.
