### ISSUE TITLE
patch-package: not found

### ISSUE THREAD

**Issue by david-pulkowski** [contentful/contentful-cli#2331]
## Expected Behavior

  node: v20.8.0
  npm: 10.1.0
  yarn: 1.22.19

npm install -g contentful-cli

added 609 packages in 21s

[12](https://github.com/UWHealth/contentful-hourly-backup/actions/runs/6456738164/job/17526825737#step:4:13)6 packages are looking for funding
  run `npm fund` for details

## Actual Behavior
npm install -g contentful-cli
...
npm ERR! path /opt/hostedtoolcache/node/20.8.0/x64/lib/node_modules/contentful-cli
npm ERR! command failed
npm ERR! command sh -c patch-package
npm ERR! sh: 1: patch-package: not found

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-10-09T[14]
Error: Process completed with exit code 127.

## Steps to Reproduce
  node: v20.8.0
  npm: 10.1.0
  yarn: 1.22.19
  npm install -g contentful-cli

1.
2.
3.
4.

## Environment
Ubuntu 22.04.3 LTS
  node: v20.8.0
  npm: 10.1.0
  yarn: 1.22.19

-   **Language Version**:
-   **Package Manager Version**:
-   **Browser Version**:
-   **Operating System**:
-   **Package Version**:

**Comment by jjolton-contentful** [comment]
reopening until release complete and verified

**Comment by jjolton-contentful** [comment]
Thanks for reporting @david-pulkowski, this is now fixed in version 3.0.1, please reach out if you are still having any issues.
