### ISSUE TITLE
contentful space use / list not working

### ISSUE THREAD

**Issue by adamgotterer** [contentful/contentful-cli#285]
## Expected Behavior

The space to be listed

## Actual Behavior

When running `contentful space list` the resulting list is empty. I'm assuming this same functionality is was powers the selection of `contentful space use`.

## Steps to Reproduce

`contentful space list`
`contentful space use`

## Environment

-   **Language Version: node 6.13.7**:
-   **Package Manager Version: 6.13.7**:
-   **Operating System: osx 10.14.3**:
-   **Package Version: 1.2.14**:

**Comment by makinwab** [comment]
Hi @adamgotterer, can you confirm that the organizations your account has access to have spaces in the web app?

Best to also update your environment with the latest packages and tools where possible.

**Comment by adamgotterer** [comment]
The issue was that the key that was automatically generated didn't have the correct perms. Unfortunately there wasn't anything that made that clear. Just a lucky guess. Closing.
