### ISSUE TITLE
'contentful guide' fails at step 3 'installing dependencies' in node v12.16.1

### ISSUE THREAD

**Issue by justJackjon** [contentful/contentful-cli#300]
## Expected Behavior
Running `contentful guide` should complete all steps, including installing any dependencies, without exiting with errors.

## Actual Behavior
Running `contentful guide` fails at step 3 during the 'Installing dependencies' sub-step with:
```
Error: Command failed: npm install
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.16.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
```

## Possible Solution
1. Use nvm and `nvm use lts/dubnium` (node v10.19.0) - This has been tested and works.
2. Install XCode (on MacBook) - Not tested.

## Steps to Reproduce
1. Run `contentful guide`
2. Run through automated steps 1 & 2 by pressing enter.
3. Fails at step 3 'Installing dependencies'

## Environment
Node Version: `v12.16.1` (works in v10.19.0)
Npm Version: `v6.13.4`
Operating System: `Darwin TDCO200022-2.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

**Comment by makinwab** [comment]
Hi @justJackjon, I'm able to run the command successfully without any of the errors you put forward.

Which version of the CLI are you using? I'm at the latest version **v1.2.33** .

**Comment by makinwab** [comment]
Oh yes, I've been able to reproduce the issue now. Didn't properly set the right node version earlier.

Thanks for bringing this up and providing a way forward. 💯
