### ISSUE TITLE
Unable to run migrations without logging into the CLI tool. 

### ISSUE THREAD

**Issue by Shy** [contentful/contentful-cli#39]
## Expected Behavior

When running `contentful space migration` you should be able to use the CLI tool without logging in if you provide an access-token with the `--access-token` argument. 

## Actual Behavior

When running `contentful space migration` you are required to log in to the CLI tool even if you provide an access-token with the `--access-token` argument. 

## Steps to Reproduce

1. Log out of the CLI tool or spin it up on a new machine. 
2. Run any migration_file using `contentful space migration --access-token $MANGEMENT_API_KEY --space-id $SPACE_ID --environment-id master migration_file.js`

## Context

I'm trying to use `contentful space migration` on circleci for a continuous integration example. Currently using the older migration tool https://github.com/contentful-labs/continous-delivery-environments-example/blob/master/.circleci/config.yml#L49

**Comment by uniteamerica-team** [comment]
I also ran into this issue where explicitly passing an `--access-token` argument to the `space migration` subcommand failed with `TypeError: Expected parameter accessToken.`

I did a bit of investigation and it looks like there's a typo in [cmds/space_cmds/migration.js#L61](https://github.com/contentful/contentful-cli/blob/0bee670c452e81cdd88909145a691073ad62e2f8/lib/cmds/space_cmds/migration.js#L61):

```
  const accessToken = argv.accesToken || cmaToken
```

It should be argv.accessToken (with two "s" characters) instead.

**Comment by mgeorgehansen** [comment]
I also ran into this issue where explicitly passing an --access-token argument to the space migration subcommand failed with TypeError: Expected parameter accessToken.

I did a bit of investigation and it looks like there's a typo in cmds/space_cmds/migration.js#L61:

  const accessToken = argv.accesToken || cmaToken
It should be argv.accessToken (with two "s" characters) instead.

**Comment by axe312ger** [comment]
@mgeorgehansen can you please open a separate issue for the (small) bug you found? :)

**Comment by Khaledgarbaya** [comment]
This will be fixed in https://github.com/contentful/contentful-cli/pull/58
