### ISSUE TITLE
Fetching content entries data fails

### ISSUE THREAD

**Issue by jarkkosyrjala** [contentful/contentful-cli#46]
## Expected Behavior

Entries data should be fetched

## Actual Behavior

Getting error `BadRequest: Status: 400 - Bad Request - Message: Response size too big, was: 9294576b. Maximum allowed response size: 7340032b.`

## Possible Solution

If there's a hard limit for the response, the response should be split to several requests.

## Steps to Reproduce

1. Run `contentful space export` for a space which has lots of content

**Comment by Khaledgarbaya** [comment]
Hey @jarkkosyrjala can you try `contentful space export --max-allowed-limit 100` more info [here](https://github.com/contentful/contentful-cli/tree/master/docs/space/export)

**Comment by axe312ger** [comment]
Closing this issue due to no traffic since January.

Feel free to comment here or open a new one if the issue arises again.
