### ISSUE TITLE
When ever I try running the cli tool I keep getting SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by hadolphs** [contentful/contentful-cli#50]
## Expected Behavior

any command with contentful to just run...

## Actual Behavior
When I run contentful (any command even --help) I get the following error:

`
$ contentful space --help
/usr/local/lib/node_modules/contentful-cli/dist/cmds/boilerplate.js:63
async function getBoilerplates() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Object.require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/contentful-cli/node_modules/require-directory/index.js:76:17`

## Steps to Reproduce

1. installed contentful with npm install -g contentful-cli
2.ran: contentful space --help

## Environment

-   **Language Version**: v.6.12.2
-   **Package Manager Version**: 5.10.0
-   **Browser Version**: safari 11.1.1 (13605.2.8)
-   **Operating System**: OS X 10.13.5 (17F77)
-   **Package Version**: 0.14.2

**Comment by hadolphs** [comment]
The tool requires node 8.  Perhaps it should be added to the documentation...

**Comment by Khaledgarbaya** [comment]
Hi @hadolphs it's already [mentioned](https://github.com/contentful/contentful-cli#cloud-installation)
