### ISSUE TITLE
Commands fail when active environment does not exist

### ISSUE THREAD

**Issue by axe312ger** [contentful/contentful-cli#509]
## Expected Behavior

When working with environments, after switching/using another space, I want the active environment reset to master

## Actual Behavior

The active environment stays the same, even when the new used/active space does not have the active environment.

In worst case this breaks many CLI commands with confusing error messages:

```sh
contentful space migration --space-id XXXXX YYYY.js -y

The provided space does not exist or you do not have access.

🚨  Migration unsuccessful
🚨  Error: The provided space does not exist or you do not have access.

🚨  Migration unsuccessful
```

## Workaround

Remove `activeEnvironmentId` from `~/.contentfulrc.json`

**Comment by mayakarabula** [comment]
closing the issue, if you still need help with this please reach out to Contentful support
