### ISSUE TITLE
Is it possible to use this library programmatically?

### ISSUE THREAD

**Issue by szimek** [contentful/contentful-cli#51]
We're currently using `https://github.com/contentful/contentful-extension-cli` to deploy our extension, but it's deprecated. I'd like to be able to deploy an extension to a specific environment, but it looks like `contentful-extension-cli` doesn't support it, so I'd need to migrate. Is it possible to use this library programmatically?

EDIT: I updated our extension to use the cli for instead of our custom script for deployments.

**Comment by axe312ger** [comment]
Hey Szymon,

unfortunately it is not possible to use it programmatically in a direct way. But what you can do, is to run the cli from node and pass your configuration to it.


Something like:

```js
const execa = require('execa');

(async () => {
        try {
	    const {stdout} = await execa('contentful', ['extension', 'create', ...]);
	    console.log(stdout);
	} catch (error) {
		console.log(error);
	}
})();
```

(I prefer [execa](https://github.com/sindresorhus/execa) but the node child_process core lib will work fine, too)

Best,
Benedikt
