### ISSUE TITLE
Parse error with --proxy arg

### ISSUE THREAD

**Issue by wuan** [contentful/contentful-cli#519]
## Expected Behavior

It should be possible to specify a proxy through arguments.

According to help it should be
```
  --proxy                   Proxy configuration in HTTP auth format:
                            [http|https]://host:port or
                            [http|https]://user:password@host:port      [string]
```

## Actual Behavior

When using a proxy url in the format `http://jenkins-squid:8080/` the following error is shown:

```
$ node_modules/contentful-cli/bin/contentful.js space export --config export_config.json --content-file contentful_export.json --mt **** --proxy http://jenkins-squid:8080/
🚨  Error: Please provide the proxy config in the following format:
host:port or user:password@host:port
┌───────────────────────────────────────────────────────────────────┐
│ Error: Please provide the proxy config in the following format:   │
│ host:port or user:password@host:port                              │
│     at parseOptions                                               │
│ (/home/jenkins/project/workspace/dump_master/node_modu…           │
│     at runContentfulExport                                        │
│ (/home/jenkins/project/workspace/dump_master/node_modu…           │
│     at exportSpace                                                │
│ (/home/jenkins/project/workspace/dump_master/node_modu…           │
│     at Object.argv [as handler]                                   │
│ (/home/jenkins/project/workspace/dump_master/node_modu…           │
│     at innerArgv.then.argv                                        │
│ (/home/jenkins/project/workspace/dump_master/node_modu…           │
└───────────────────────────────────────────────────────────────────┘
error Command failed with exit code 1.
```

The same error occurs when using the format proposed in the error message above:
```
$ node_modules/contentful-cli/bin/contentful.js space export --config export_config.json --content-file contentful_export.json --mt **** --proxy jenkins-squid:8080
```

## Possible Solution

  * fix parse error
  * adapt help text to reflect required format

## Steps to Reproduce

1. Try to run contentful-cli using a proxy with arg `--proxy http://host:port` or `--proxy host:port` 

## Context

We wanted to export an environment as a step in a Jenkins pipeline.

## Environment

-   **Language Version**: v10.20.1
-   **Package Manager Version**: 6.14.4
-   **Browser Version**: n/a
-   **Operating System**: Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 GNU/Linux
-   **Package Version**: contentful-cli@1.4.17

**Comment by wuan** [comment]
I just saw, that the existence of a env variable takes precedence over the parameter, will check that now.

**Comment by wuan** [comment]
Found the place where it goes wrong:

https://github.com/contentful/contentful-cli/blob/087c163b846d99be1585155e19c681ab88d847cd/lib/cmds/space_cmds/export.js#L162

This converts the incoming `string` (not a proxy object) like `127.0.0.1:123` to `http:` which is an invalid proxy definition.

**Comment by andreascful** [comment]
Hello,

sorry for the long delayed response. This error should have been fixed in previous versions.
In case of special proxy strings I'd recommend to use the "rawProxy" parameter in addition to the proxy configuration like this: `contentful space export --proxy 127.0.0.1:5555 --rawProxy`. That way the proxy argument is not being formatted by the client.

I'm closing this issue for now. If you still face any issues with the configuration please open another ticket.
