### ISSUE TITLE
Can’t import webhooks with JSON pointers in url

### ISSUE THREAD

**Issue by spitlo** [contentful/contentful-cli#577]
## Expected Behavior

I’m running `contentful export` with the `--skip-content` flag to export my space setup as a scaffold for other projects. The space has webhooks set up, and the webhooks use JSON pointers in them.

Example url with JSON pointers (from the docs):

```json
{
  "name": "Dynamic URL",
  "url": "https://my-webhook-endpoint.com/{ /payload/sys/id }"
}
```

I would expect to be able to import the resulting document into another space.

## Actual Behavior

When I try to import the resulting file, I get the a `ValidationError` with the message: `"url" must be a valid uri`

Since JSON pointers are allowed in the `url` field according to [the documentation](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/webhooks), the import validator should allow them as well.

## Steps to Reproduce

1. Export a space with a webhook using JSON pointers in url
2. Import the resulting file into another space

## Context

Webhooks (especially webhooks with custom payload in localized spaces) are pretty time consuming to set up. Not being able to export and later import them increases my workload unnecessarily. We have many similar projects, and I would prefer to only have to change the credentials in each space/environment, not manually setup the exact same 15+ webhooks for each env in each space.

## Environment

-   **Node Version**: 13.12.0
-   **Package Manager Version**: yarn 1.22.4
-   **Operating System**: Darwin
-   **Package Version**: 1.4.28

**Comment by marcolink** [comment]
Hi @spitlo,
thanks for your feedback. 🎉 

This has been fixed in [contentful-import@7.9.32](https://github.com/contentful/contentful-import/releases/tag/v7.9.32) and is included in `contentful-cli`  >= `1.5.3`

Feel free to open this issue again if you feel things are not working as expected.
