### ISSUE TITLE
[Question] Is it possible to remove all assets/media from an environment or remove all existing entries/models when doing an import? 

### ISSUE THREAD

**Issue by Ortimis** [contentful/contentful-cli#581]
Which content_type is to be used if I do not want to delete entries of a specific content type, but media assets instead?

Answer to the former has been given in https://github.com/contentful/contentful-cli/issues/89 , but only for entries, not for assets.

Thank you!

**Comment by Ortimis** [comment]
Worked with

```
client.getSpace(CONTENTFUL_SPACE_ID)
	.then(space => space.getEnvironment(CONTENTFUL_ENV_NAME))
	.then(environment => environment.getAssets())
    .then(response => Promise.all(response.items.map(entry => entry.delete())))
    .catch(error => console.log(error))
```

**Comment by rafalschmidt97** [comment]
Try this:

https://github.com/contentful/contentful-cli/issues/89#issuecomment-693338736
