### ISSUE TITLE
Import option to completely overwrite everything within a space

### ISSUE THREAD

**Issue by geoffhardy1** [contentful/contentful-cli#64]
## Expected Behavior

When importing into Contentful, it would be great to have an option to overwrite everything within a space. All existing content types, entries and assets would be discarded and replaced by the imported file.

## Actual Behavior

Currently, import is additive only - that this, any existing content types, entries and assets remain in the database.

## Possible Solution

This could be an option specified when running the import, eg. "overwrite".

## Context

We have a number of different spaces for our environments, such as PROD, TEST and DEV. Frequently we want to take a copy of what is in PROD and import into the other environments, such as TEST or DEV. When we do this, we have to run a script that goes through and deletes each entry, content type and asset separately. This is very time-consuming and inefficient. 

Alternatively, if there was a quick way to just delete everything in a space, this would be a step that we could run before the import.

**Comment by axe312ger** [comment]
The import tool is client side and would have to do exactly the same. Run a delete request for everything it finds. Means that we can't speed it up on the CLI end.

Why not just deleting TEST or DEV environment and recreating it? That way our backend duplicates your PROD environment within a few seconds/minutes.

As long you keep the same environment id, this should be working out pretty good (Except TEST/DEV downtime while it is recreating them)

Does this helP?

**Comment by geoffhardy1** [comment]
Currently we have been using a separate space for DEV, TEST, PROD, etc. Switching to use environments for DEV and TEST is an option that we have been considering. We will give this a try.
