### ISSUE TITLE
Environment id is not supported for getting a content type

### ISSUE THREAD

**Issue by lucasvanlierop** [contentful/contentful-cli#65]
## Expected Behavior

When requesting a content type and specifying the space and the content_type should be retrieved from that space and content type, e.g:

`contentful --space-id foospace --environment-id barvironment content-type get --id bazcontenttype`

## Actual Behavior

The environment id is ignored and the master id is selected

## Possible Solution

Allow specifying the `--environment` argument here:
https://github.com/contentful/contentful-cli/blob/56482f91f6a1d18108f9be8ec93322f349c40553/lib/cmds/content-type_cmds/get.js#L17

-   **Package Version**: Contentful CLI 0.14.2

**Comment by Khaledgarbaya** [comment]
HI @lucasvanlierop,
Thanks for reporting this, we'll get to it as soon as possible.
Meanwhile, PRs are more than welcome.

Best,
Khaled

**Comment by M3kH** [comment]
Hi @Khaledgarbaya 👋 
Me and @lucasvanlierop we are looking into it. I guess we can fix it between today and tomorrow.
