### ISSUE TITLE
Command "space migration" ignores active environment from .contentfulrc.json

### ISSUE THREAD

**Issue by ristomatti** [contentful/contentful-cli#68]
## Expected Behavior

When doing:
```
$ contentful space environment use -e "some-env"
$ contentful space migration some-script.js
```
I would expect migration to be run against "some-env" environment.

## Actual Behavior

The confirmation dialog shows active environment is ignored:
```
The following migration has been planned

Environment: master

Create Content Type testContent
  - name: "Test content"
  - description: ""
```

## Possible Solution

Consistently support space and environment set in `.contentfulrc.json` to act as default space and environment parameters.

## Environment
- **Node Version:** v8.11.3
- **Npm Version:** 6.1.0
- **Package Version:** 0.16.0

**Comment by Khaledgarbaya** [comment]
Hey @ristomatti,
You are right and we'll tackle this issue soon.
Meanwhile PRs are welcome, the active environment needs to be grabbed here https://github.com/contentful/contentful-cli/blob/master/lib/cmds/space_cmds/migration.js#L59 and adding the check later.

Best,
Khaled
