### ISSUE TITLE
Contentful Guide - error unable to get local issuer certificate

### ISSUE THREAD

**Issue by Tonyhliu** [contentful/contentful-cli#693]
## Expected Behavior

contentful guide command to succeed

## Actual Behavior

erroring out after confirming "Space Creation"

## Steps to Reproduce

1. $ contentful guide
2. create new space now? select Y
3. confirm space creation? select Y

-> 🚨  Error: unable to get local issuer certificate

## Environment

Node Version: 10.23.0
Npm Version: 6.14.8
Operating System: Darwin LM-SJN-40015506 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
Package Version: 1.4.62

**Comment by justintime4tea** [comment]
What was the issue here ultimately? Experiencing the same 😞
