### ISSUE TITLE
Data migration is not performed within transaction

### ISSUE THREAD

**Issue by abramenal** [contentful/contentful-cli#702]
## Expected Behavior

In order to keep data consistency and integrity `contentful space migration` should implement transactions.
It means that any error faced during migration should lead to full rollback of that migration batch.

## Actual Behavior

When running migration I see `Error: Batch failed` in console and some static logs file, but the data In Contentful is modified.

## Possible Solution

One of possible ways of solving that is to perform validation round:
- before it starts changing anything, so validity is becoming a prerequisite
- after changing all records

By these 2 factors we can assume data integrity and consistency is still there.

## Steps to Reproduce

1. `contentful space migration --space-id=<space-id> <filename>.js`

## Context

I have a model with 2 required fields and 50 entities under it. 1 of that 50 is initially invalid, that means there's a required field that is empty.

So I assume what actually happens is – it rolls out migration for each affected record independently
- change a record and make it _CHANGED_
- try to _PUBLISH_ the changes for a record

PS
This single entity is invalid because of the following steps:
- create field that references Asset (e.g. image)
- introduce validation rule that enforces this field be not null
- at some point of time, remove that referenced Asset

Now you have initially invalid entity I'm referring to.

## Environment

-   **Language Version**: `node@12.2.0`
-   **Package Manager Version**: `npm@6.9.0`
-   **Package Version**: `contentful-cli@1.4.66`

**Comment by mayakarabula** [comment]
closing the issue, if you still need help with this please reach out to Contentful support

**Comment by sascha-wolf** [comment]
This was closed as completed, so presume there's a way to run migrations safely with an option to rollback in case of error?
