### ISSUE TITLE
Installed on Big Sur and everything went wrong 😭

### ISSUE THREAD

**Issue by joshuabaker** [contentful/contentful-cli#714]
Diagnosing specifically what went wrong initially is likely going to be impossible now, however, installing this package earlier today resulted in my local `node`/`npm` installs on macOS Big Sur becoming completely unusable. 

After installing `contentful-cli` via `brew` all calls to `npm` system wide would result in the same error...

```
Error: Cannot find module '../lib/cli' 
```

Looking through the code now, it looks like this surfaced [here](https://github.com/contentful/contentful-cli/blob/ba28cb3f210dbf23095ebd4dfb78c22f124deb64/bin/contentful.js#L3).

After removing via `brew` the `npm` install remained broken with various other errors, and I’ve actually been unable to recover from this.

Do you have any idea why/how this package could’ve caused all this?

_I don’t have exact version numbers, but at the time of install Node was v12.x. The OS is macOS Big Sur v11.0.1._

**Comment by juanibiapina** [comment]
I have a similar error after running `npm install -g contentful-cli` to upgrade the module. The line
```
require('../output/lib/cli.js')
```

refers to a file that doesn't exist.

**Comment by mayakarabula** [comment]
thanks for reporting @juanibiapina , fixing it now
