### ISSUE TITLE
`Import` a space throws `Rate limit error`

### ISSUE THREAD

**Issue by AmrAbdulrahman** [contentful/contentful-cli#79]
## Actual Behavior
When I run
```
contentful space import --space-id <id>   --content-file contentful-export.json  --content-model-only --skip-locales --skip-content-publishing
```

I always get the same error
```
13:20:73 - Rate limit error occurred. Waiting for 1568 ms before retrying...
```

## Steps to Reproduce

1. `export` a space into a file
1. `import` the exported space into a newly created space

## Environment

- Node: v8.10.0
- npm 5.6.0
- OS: macOS 10.13.4

## Screenshot
![Image of Yaktocat](https://preview.ibb.co/gK50hp/Screen_Shot_2018_08_27_at_13_32_45.png)

**Comment by AmrAbdulrahman** [comment]
Figured out it was just a warning and not an error 🙈
That said, the success message should be listed *after* the warnings.

**Comment by axe312ger** [comment]
Good point @AmrAbdulrahman, I created a internal ticket to do this next time we add features to this tool :)

**Comment by cajoy** [comment]
Have the same issue. But after number of retries to fails with 409 

```
0:07:99 - Rate limit error occurred. Waiting for 1565 ms before retrying...
10:07:00 - Rate limit error occurred. Waiting for 1585 ms before retrying...
10:07:04 - Rate limit error occurred. Waiting for 1561 ms before retrying...
10:07:67 - Connection error occurred. Waiting for 1965 ms before retrying...
10:08:20 - Server 504 error occurred. Waiting for 1919 ms before retrying...
10:08:36 - VersionMismatch: Status: 409 - Conflict - Message:  - Request ID: 0154bdf8a57fee7087f5c89081edbde8
```

**Comment by tuliofaria** [comment]
I was facing the same error while importing my content/content-types to a new space. The problem was a published content referencing an achieved one (the achieved one does not exist on the new space (because it was not exported) - so it is not able to execute the creation of this content (the published one). Since the cli tries over and over, it raises the ´Rate limit error...`.

**Comment by gairon** [comment]
Got error `VersionMismatch: Status: 409 - Conflict` while importing Tags. Any reasons why it might happen? At the same time some of tags imported without errors, some with error `VersionMismatch`, couldn't find correlation :(
