### ISSUE TITLE
SyntaxError on windows with ts-node

### ISSUE THREAD

**Issue by D0m3-** [contentful/contentful-cli#809]
## Expected Behavior

ts-node and contentul-cli to work properly when used together on windows

## Actual Behavior

```
> ts-node node_modules/.bin/contentful space migration "contentful/migrations/03-product-slug.ts"

C:\Users\shogo\Projects\Perso\makramonde-next\node_modules\.bin\contentful:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

## Possible Solution

point to contentful-cli directly 
```
ts-node node_modules/contentful-cli/bin/contentful.js space migration
```

## Environment

Node v15.2.0
Windows 10
ts-node 9.1.1
contentful-cli@1.5.28

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
