### ISSUE TITLE
Import does not allow creation of public tags

### ISSUE THREAD

**Issue by anshumanb** [contentful/contentful-cli#880]
## Expected Behavior
Public tags can be imported

## Actual Behavior
Tags are always created as private, even those that have `sys.visibility` set to `public`.

## Possible Solution
Make [`createTagInDestination`](https://github.com/contentful/contentful-import/blob/c27f23d60a36f5812f1ca2a12eaf696f3af6fa2f/lib/tasks/push-to-space/creation.js#L153) pass the visibility flag through to [`createTag`](https://github.com/contentful/contentful-management.js/blob/0d9481d0bdf0a021fb148895f04510fad3f4e006/lib/create-environment-api.ts#L1245).

## Steps to Reproduce

1. Ensure no tag exists with the id `myPublicTag`
2. Create a file `tag.json` with the following contents:
    ```
    {
      "tags": [
        {
          "sys": {
            "id": "myPublicTag",
            "type": "Tag",
            "version": 1,
            "visibility": "public"
          },
          "name": "My public tag"
        }
      ]
    }
    ```
3. Run `npx contentful-cli space import --content-file tag.json`
4. "My public tag" is created as a private tag

## Context
I'm trying to migrate over tags, both public and private, over to Contentful from our current CMS but am not able to add public tags through the import tool. Hitting the API directly with cURL works though. I found the issue is with `contentful-import`.

## Environment
```
$ npx contentful-cli --version
1.5.35
```

**Comment by mbyrne00** [comment]
Still an issue in version `1.6.12`. And in the UI you can't change visibility so this is a real blocker.

**Comment by makinwab** [comment]
This issue has been addressed in recent versions of the dependent packages and the CLI. You can update to the latest version of the CLI `v1.8.6`.
