### ISSUE TITLE
[Question] Is it possible to remove all entries/models from an environment or remove all existing entries/models when doing an import?

### ISSUE THREAD

**Issue by rtm619** [contentful/contentful-cli#89]
Hi,

Is it possible to remove all entries/models of an environment using the contentful-management API/module? 

Also, is it possible to remove all existing entries/models when doing an import to an environment?

**Comment by Khaledgarbaya** [comment]
Hey @rtm619,

Yes, that is possible,

```js
client.getSpace('spaceId')
	.then(space => space.getEnvironment('environmentId'))
	.then(envrionment => environment.getEntries({'content_type': 'myContentTypeId'}))
    .then(response => Promise.all(response.items.map(entry => entry.delete())))

// after that you can delete the content Type
```

**Comment by rafalschmidt97** [comment]
https://github.com/jugglingthebits/contentful-clean-space

**Comment by romanzWizz** [comment]
Probably someone will face with an issue when you try to delete too many items and API just crashes.
Another trouble can be when you have both published and unpublished entries. 

I would recommend handling these issues this way:

```
  getEnvironment()
    .then(env => env.getEntries({ content_type: 'myContentTypeId ' }))
    .then(async response => {
      for (const entry of response.items) {
        if (!entry.sys.publishedVersion) {  // <= check if entry in Draft mode, we can immediately delete
          await entry.delete();
        } else {
          await entry.unpublish().then(e => e.delete());  // <= otherwise, we need to unpublish first
        }
      }
    });
```

**Comment by andykimchris** [comment]
@Roman-ZN @Khaledgarbaya why is the request returning `TypeError: entry.delete is not a function `
