### ISSUE TITLE
Space export missing assets downloaded

### ISSUE THREAD

**Issue by seejamescode** [contentful/contentful-cli#92]
## Expected Behavior

The following command will have an `assets` folder saved to my computer:

```bash
contentful space export --space-id [scrubbed id] --download-assets
```

## Actual Behavior

Can find the json file, but no assets folder. Here is the output:

```bash
✔ Initialize client (1s)
 ✔ Fetching data from space
   ✔ Connecting to space (2s)
   ✔ Fetching content types data (1s)
   ✔ Fetching editor interfaces data (1s)
   ✔ Fetching content entries data (1s)
   ✔ Fetching assets data (1s)
   ✔ Fetching locales data (1s)
   ✔ Fetching webhooks data (1s)
   ✔ Fetching roles data (1s)
 ✔ Download assets (5s)
 ✔ Write export log file
   ✔ Lookup directory to store the logs
   ✔ Create log directory
   ✔ Writing data to file
┌────────────────────────┐
│ Exported entities      │
├───────────────────┬────┤
│ Content Types     │ 2  │
├───────────────────┼────┤
│ Editor Interfaces │ 2  │
├───────────────────┼────┤
│ Entries           │ 16 │
├───────────────────┼────┤
│ Assets            │ 33 │
├───────────────────┼────┤
│ Locales           │ 1  │
├───────────────────┼────┤
│ Webhooks          │ 0  │
├───────────────────┼────┤
│ Roles             │ 0  │
└───────────────────┴────┘
┌─────────────────────────────┐
│ Asset file download results │
├──────────────────┬──────────┤
│ Successful       │ 33       │
├──────────────────┼──────────┤
│ Warnings         │ 0        │
├──────────────────┼──────────┤
│ Errors           │ 0        │
└──────────────────┴──────────┘
The export took a few seconds (8s)

Stored space data to json file at: /Users/jamesrauhut/contentful-export-[scrubbed]-master-2018-11-02T11-09-35.json
No errors or warnings occurred
The export was successful.
✨ Done
```

## Environment

Node Version: v8.11.3
Npm Version: 5.6.0
Operating System: 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
Package Version: 0.16.1

**Comment by Khaledgarbaya** [comment]
Hey @seejamescode,
At first glance, this should work because we are passing the param [here](https://github.com/contentful/contentful-cli/blob/master/lib/cmds/space_cmds/export.js#L63) I'll need to investigate that.

**Comment by seejamescode** [comment]
Thanks! If anything, it would be great to have text telling me where the assets were attempted to be saved at. I did try a system-wide search for the file names.

**Comment by Khaledgarbaya** [comment]
hey @seejamescode usually it should in the same directory as your exported json file

**Comment by seejamescode** [comment]
Oh yep! Found `images.ctfassets.net/` and `videos.ctfassets.net/` in that folder. It would be helpful to either have that logged next to the `Stored space data...` message or include json and those folders in a single new folder.
