### ISSUE TITLE
Rich text editor returning contentful app prefix on URLs / INLINES.HYPERLINK

### ISSUE THREAD

**Issue by openbook** [contentful/contentful-cli#93]
## Expected Behavior

* API value returned from rich text editor should return links with no prefix

## Actual Behavior

* Links are being returned as:
`
'https://app.contentful.com/&quot;[link value]/&quot;' 
`

So the full return value is:

```
{
  data:  {
    uri: 'https://app.contentful.com/&quot;[LINK]/&quot;' },
    content: [ 
      { 
        data: {},
        marks: [],
        value: [LINK TEXT],
        nodeType: 'text' 
      } 
    ]
}}
```

## Possible Solution

Remove 'https://app.contentful.com/&quot;/&quot;'

## Steps to Reproduce

1. Use the new beta rich text field to create text containing links
2. retrieve the value from CDN API

## Environment

contentful-cli version 0.16.1

**Comment by Khaledgarbaya** [comment]
Hey @openbook,
Let investigate this and get back to you

**Comment by openbook** [comment]
This looks like it's actually caused by the links being imported into a markdown field via the CLI then migrated to the rich text field, so, I think this issue as is, can be closed.
