### ISSUE TITLE
Make error message "You cannot edit field "" on content type "" because it does not exist." more clear

### ISSUE THREAD

**Issue by ZwaarContrast** [contentful/contentful-cli#94]
## Expected Behavior

I would expect the Error message to be more clear about the fact that the content type does not exist.

## Actual Behavior

`You cannot edit field "components" on content type "page" because it does not exist.`

## Possible Solution

For example:
`You cannot edit field "components" on content type "page" because the content type does not exist`

## Steps to Reproduce

1. Run a migration on a non-existing content type: `migration.editContentType('DOES NOET EXIST')`
2. Try and edit a field `page.editField('fieldName')`

## Context

I was stuck because i was trying to figure out why the field 'components' could not be found. The actual error was that the content type did not exist.

## Environment
Not relevant

**Comment by bundance** [comment]
Not sure why this has been closed. The issue raised has just confused me as well, and if it wasn't for this issue, I'd still be stuck now. I think this issue should be reopened, as it's such a simple fix.

**Comment by phoebeschmidt** [comment]
hi @bundance,

we are accepting PRs in contentful-migration: https://github.com/contentful/contentful-migration
here's the relevant file: https://github.com/contentful/contentful-migration/blob/0203edf5267b07450ae0cb73e37660d5c456185f/src/lib/migration-chunks/validation/errors.ts

Cheers,
Phoebe

**Comment by phoebeschmidt** [comment]
@bundance this has been fixed as the above PR has been merged.
