### ISSUE TITLE
Typings or values incorrect for validations when running space generate migration command

### ISSUE THREAD

**Issue by ZwaarContrast** [contentful/contentful-cli#95]
## Expected Behavior

According to the typings of  the `assetImageDimensions` field on `IValidation` the values for `width.min`, `width.max`, `height.min` and `height.max` are either are number or undefined.

## Actual Behavior

When running the `contentful space generate migration` command, the generated values for the `assetImageDimensions` fields are can be null when you have not configured them in the UI:

![screenshot 2018-11-13 10 35 58](https://user-images.githubusercontent.com/1869392/48404201-0d286e00-e730-11e8-840d-1e88a0b2a797.png)

Generated validations function:
```
.validations([
      {
        assetImageDimensions: {
          width: {
            min: 200,
            max: null
          },

          height: {
            min: null,
            max: null
          }
        }
      }
    ])
```
## Possible Solution

Either adjust the typings if the behaviour of the command is correct, or adjust the functionality to not have null values but leave them out (undefined).

Adjust typings
```

export interface IValidation {
 ...
  /** Validates that an image asset is of a certain image dimension. */
  assetImageDimensions?: { width: { min?: number | null , max?: number | null }, height: { min?: number | null , max?: number | null } }
...
}
```
Or make sure the output is:
```
.validations([
      {
        assetImageDimensions: {
          width: {
            min: 200,
          },
        }
      }
    ])
```

## Steps to Reproduce
1. Create a contentType in the Contentful UI
2. Add a field of type Media
3. Add validation for `Accept only specified image dimensions`, only set a rule for `width` of  `atleast 200px`
4. Save content type
5. Run command `yarn run ts-node node_modules/.bin/contentful space generate migration -s XXX -e XXX -c XXX`

Result: 

```
module.exports = function(migration) {
  const test = migration
    .createContentType("test")
    .name("test")
    .description("");

  test
    .createField("test")
    .name("test")
    .type("Link")
    .localized(false)
    .required(false)
    .validations([
      {
        assetImageDimensions: {
          width: {
            min: 200,
            max: null
          },

          height: {
            min: null,
            max: null
          }
        }
      }
    ])
    .disabled(false)
    .omitted(false)
    .linkType("Asset");

  test.changeEditorInterface("test", "assetLinkEditor", {});
};
```

**Comment by Khaledgarbaya** [comment]
Hi @ZwaarContrast,
Thanks for spotting that out we'll try to fix it asap. Meanwhile PRs are welcome if you want to take stab at it

**Comment by makinwab** [comment]
Re: https://github.com/contentful/contentful-migration/issues/312
I've routed this issue to the appropriate repo issues list and thus closing this.
