### ISSUE TITLE
Management Token for Extension Commands

### ISSUE THREAD

**Issue by dtothefp** [contentful/contentful-cli#96]
## Expected Behavior
If the user does not perform `contentful login`, extension commands can be used by passing a `--management-Token` option, ex.

```
contentful extension list --space-id $CONTENTFUL_SPACE --management-token $CONTENTFUL_CMA_TOKEN
```

## Actual Behavior
Command actually throws because the management token for `extension_cmds` commands is not parsed and applied the same way that is for `space_cmds`

```
contentful extension list --space-id $CONTENTFUL_SPACE --management-token $CONTENTFUL_CMA_TOKEN

🚨  Error: Expected parameter accessToken
│ TypeError: Expected parameter accessToken                                                                                           │
│      at createClient                                                                                                                │
│ (/.config/yarn/global/node_modules/contentful-management/dist/contentful-management.node.js:6894:11)             │
│      at createManagementClient                                                                                                      │
│ (/.config/yarn/global/node_modules/contentful-cli/dist/utils/contentful-clients.js:26:49)                        │
│      at <anonymous> 
```

## Possible Solution
Add the `argv.token` parsing / argument to where `createManagementClient` is called in the extensions commands. I would also be happy to put forth a PR for this

ex.

```js
  const client = await createManagementClient({
    accessToken: argv.managementToken || cmaToken,
    feature: 'extension-list'
  })
```

## Steps to Reproduce

1. Do NOT run contentful login
2. Generate a CMA personal token
3. Add it to your environment `export CONTENTFUL_CMA_TOKEN=<your_token>`
4. Run an `extension` command `contentful extension list --space-id $CONTENTFUL_SPACE --management-token $CONTENTFUL_CMA_TOKEN`

## Context
Deploy extension in CI with encrypted CMA token

## Environment

-   **Language Version**: Node@8.10.0
-   **Package Manager Version**: yarn@1.12.1
-   **Browser Version**: NA
-   **Operating System**: MacOS@10.12.6
-   **Package Version**: 0.16.1

**Comment by dtothefp** [comment]
@Khaledgarbaya any thoughts on this? I'd like to automate my deploys of extensions in CI and looks like this is the only way. I can put up a PR

**Comment by Khaledgarbaya** [comment]
Hey @dtothefp,
We'll try to take care of this as soon as possible meanwhile if you are interested in fixing this PRs are very welcome!

**Comment by Khaledgarbaya** [comment]
Fixed in https://github.com/contentful/contentful-cli/pull/107
