### ISSUE TITLE
 TypeError: createManagementClient(...).getSpace is not a function

### ISSUE THREAD

**Issue by billhennessy** [contentful/contentful-cli#99]
REPO:
* Install Contentful CLI
* Log in from command line with personal access token
* Attempt to generate migration script with `contentful space generate migration -s [space-id] -e master`

## Expected Behavior
Script generated

## Actual Behavior
Error: createManagementClient(...).getSpace is not a function

## Possible Solution

None found

## Steps to Reproduce
See above

1.
2.
3.
4.

## Environment

-   **Language Version**:
-   **Package Manager Version**:
-   **Browser Version**:
-   **Operating System**:
-   **Package Version**:

**Comment by phoebeschmidt** [comment]
Hi @maximilian-lindsey and @billhennessy,

Just letting you know this has been fixed with #101 and was released in v0.17.1 🎉

**Comment by billhennessy** [comment]
Thanks, Phoebe. I just successfully generated my migration!

**Comment by zetlan** [comment]
I'm on 0.17.2 and getting this error. Can we re-open?

**Comment by phoebeschmidt** [comment]
@zetlan thanks for pointing this out. It was a hitch in our npm release-- v0.17.3 is now out and fixes this.
